"""add trip_places table with custom place support

Revision ID: 6da59ea1a0a2
Revises: c959f3a75fd4
Create Date: 2026-07-16 16:18:58.118535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6da59ea1a0a2'
down_revision: Union[str, Sequence[str], None] = 'c959f3a75fd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_places',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=True),
    sa.Column('custom_name', sa.String(), nullable=True),
    sa.Column('custom_city', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('visit_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_places_trip_id'), 'trip_places', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_places_trip_id'), table_name='trip_places')
    op.drop_table('trip_places')
    # ### end Alembic commands ###
