"""add hotels table

Revision ID: 8607f5bfb30c
Revises: 412846b9ec44
Create Date: 2026-07-17 10:24:32.684019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8607f5bfb30c'
down_revision: Union[str, Sequence[str], None] = '412846b9ec44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('budget_tier', sa.String(), nullable=False),
    sa.Column('price_per_night', sa.Float(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotels_budget_tier'), 'hotels', ['budget_tier'], unique=False)
    op.create_index(op.f('ix_hotels_city'), 'hotels', ['city'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hotels_city'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_budget_tier'), table_name='hotels')
    op.drop_table('hotels')
    # ### end Alembic commands ###
