"""add restaurants table

Revision ID: c3cf2b6cbd8c
Revises: 8607f5bfb30c
Create Date: 2026-07-17 10:53:17.856168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3cf2b6cbd8c'
down_revision: Union[str, Sequence[str], None] = '8607f5bfb30c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('budget_tier', sa.String(), nullable=False),
    sa.Column('avg_cost_per_person_per_day', sa.Float(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurants_budget_tier'), 'restaurants', ['budget_tier'], unique=False)
    op.create_index(op.f('ix_restaurants_city'), 'restaurants', ['city'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restaurants_city'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_budget_tier'), table_name='restaurants')
    op.drop_table('restaurants')
    # ### end Alembic commands ###
