"""add distance tracking columns to trips

Revision ID: cb8c7383cd39
Revises: 6da59ea1a0a2
Create Date: 2026-07-17 08:31:40.237493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb8c7383cd39'
down_revision: Union[str, Sequence[str], None] = '6da59ea1a0a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('total_distance_km', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('distance_saved_km', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'distance_saved_km')
    op.drop_column('trips', 'total_distance_km')
    # ### end Alembic commands ###
