"""add external_place_id and last_synced_at to places

Revision ID: d8ff82d17bd4
Revises: c3cf2b6cbd8c
Create Date: 2026-07-18 11:44:25.772385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8ff82d17bd4'
down_revision: Union[str, Sequence[str], None] = 'c3cf2b6cbd8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('external_place_id', sa.String(), nullable=True))
    op.add_column('places', sa.Column('last_synced_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_places_external_place_id'), 'places', ['external_place_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_places_external_place_id'), table_name='places')
    op.drop_column('places', 'last_synced_at')
    op.drop_column('places', 'external_place_id')
    # ### end Alembic commands ###
